### ISSUE TITLE
is this ready for usage?

### ISSUE THREAD

**Issue by Almenon** [gitops-bridge-dev/gitops-bridge-argocd-bootstrap-terraform#11]
Thanks for making this! Much cleaner to have the bootstrap in its own repo. I was in the middle of configuring our code with the old bootstrap module when I noticed this one. Is this ready to use?

**Comment by csantanapr** [comment]
Hi @Almenon 

Yes is ready for use
Check out the examples

- [argocd-ingress](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/argocd-ingress)
- [aws-secrets-manager](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/aws-secrets-manager)
- [crossplane](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/crossplane)
- [external-secrets](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/external-secrets)
- [multi-cluster/distributed](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/multi-cluster/distributed)
- [multi-cluster/hub-spoke](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/multi-cluster/hub-spoke)
- [multi-cluster/hub-spoke-shared](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/multi-cluster/hub-spoke-shared)
- [private-git](https://github.com/gitops-bridge-dev/gitops-bridge/tree/main/argocd/iac/terraform/examples/eks/private-git)
-

**Comment by csantanapr** [comment]
@Almenon 
Give us feedback, you can find me in argo-cd channel in CNCF Slack https://slack.cncf.io
