### ISSUE TITLE
Publish the module to the terraform registry

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge-argocd-bootstrap-terraform#13]
Publish the module to the terraform registry

**Comment by jomakori** [comment]
+1

**Comment by csantanapr** [comment]
@jomakori The module is published on terraform registry here https://registry.terraform.io/modules/gitops-bridge-dev/gitops-bridge/helm/latest
There is a new github repo that replaces this one https://github.com/gitops-bridge-dev/terraform-helm-gitops-bridge
